/**
 * Copyright (c) 2023 John Toebes
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
export const DIR2 = 1 // Direct/REL, used only for BRSET and BRCLR
export const DIR = 2 // Direct, 1 byte address (high byte is 0x00)
export const EXT = 3 // Extended, 2 byte address
export const REL = 4 // Relative, 1 byte signed offset (branches only)
export const INH = 5 // Inherent, no arg
export const IX = 6 // Indexed, no offset
export const IX1 = 7 // Indexed, 1 byte unsigned offset
export const IX2 = 8 // Indexed, 2 byte unsigned offset
export const IMM = 9 // Immediate, 1 byte arg
export const DB = 10 // Illegal instruction, use a DB
export const BSC = 11 // Bit set/clear instructions

export const CAT_INH = 1 << 8
export const CAT_REL = 2 << 8
export const CAT_BSC = 3 << 8
export const CAT_BSCX = 4 << 8
export const CAT_BTB = 5 << 8
export const CAT_BTBX = 6 << 8
export const CAT_IMM_DIR_EXT_IX1_IX1_IX = 7 << 8
export const CAT_DIR_EXT_IX1_IX1_IX = 8 << 8
export const CAT_DIR_IX1_IX = 9 << 8
export const CAT_ALIGN = 10 << 8
export const CAT_DB = 11 << 8
export const CAT_DS = 12 << 8
export const CAT_DW = 13 << 8
export const CAT_EQU = 14 << 8
export const CAT_INCLUDE = 15 << 8
export const CAT_TIMEX = 16 << 8
export const CAT_TIMEX6 = 17 << 8
export const CAT_IF = 18 << 8
export const CAT_ELSE = 19 << 8
export const CAT_ENDIF = 20 << 8

export interface keywordDefinitions {
    name: string
    value: number
}

export const aKeyWords: keywordDefinitions[] = [
    { name: 'ADC', value: CAT_IMM_DIR_EXT_IX1_IX1_IX | 0xa9 },
    { name: 'ADD', value: CAT_IMM_DIR_EXT_IX1_IX1_IX | 0xab },
    { name: 'ALIGN', value: CAT_ALIGN | 0 },
    { name: 'AND', value: CAT_IMM_DIR_EXT_IX1_IX1_IX | 0xa4 },
    { name: 'ASL', value: CAT_DIR_IX1_IX | 0x38 },
    { name: 'ASLA', value: CAT_INH | 0x48 },
    { name: 'ASLX', value: CAT_INH | 0x58 },
    { name: 'ASR', value: CAT_DIR_IX1_IX | 0x37 },
    { name: 'ASRA', value: CAT_INH | 0x47 },
    { name: 'ASRX', value: CAT_INH | 0x57 },
    { name: 'BCC', value: CAT_REL | 0x24 },
    { name: 'BCLR', value: CAT_BSCX | 0x11 },
    { name: 'BCLR0', value: CAT_BSC | 0x11 },
    { name: 'BCLR1', value: CAT_BSC | 0x13 },
    { name: 'BCLR2', value: CAT_BSC | 0x15 },
    { name: 'BCLR3', value: CAT_BSC | 0x17 },
    { name: 'BCLR4', value: CAT_BSC | 0x19 },
    { name: 'BCLR5', value: CAT_BSC | 0x1b },
    { name: 'BCLR6', value: CAT_BSC | 0x1d },
    { name: 'BCLR7', value: CAT_BSC | 0x1f },
    { name: 'BCS', value: CAT_REL | 0x25 },
    { name: 'BEQ', value: CAT_REL | 0x27 },
    { name: 'BHCC', value: CAT_REL | 0x28 },
    { name: 'BHCS', value: CAT_REL | 0x29 },
    { name: 'BHI', value: CAT_REL | 0x22 },
    { name: 'BHS', value: CAT_REL | 0x24 },
    { name: 'BIH', value: CAT_REL | 0x2f },
    { name: 'BIL', value: CAT_REL | 0x2e },
    { name: 'BIT', value: CAT_IMM_DIR_EXT_IX1_IX1_IX | 0xa5 },
    { name: 'BLO', value: CAT_REL | 0x25 },
    { name: 'BLS', value: CAT_REL | 0x23 },
    { name: 'BMC', value: CAT_REL | 0x2c },
    { name: 'BMI', value: CAT_REL | 0x2b },
    { name: 'BMS', value: CAT_REL | 0x2d },
    { name: 'BNE', value: CAT_REL | 0x26 },
    { name: 'BPL', value: CAT_REL | 0x2a },
    { name: 'BRA', value: CAT_REL | 0x20 },
    { name: 'BRSKIP', value: CAT_INH | 0x21 },
    { name: 'BRSKIP2', value: CAT_INH | 0xc5 },
    { name: 'BRCLR', value: CAT_BTBX | 0x01 },
    { name: 'BRCLR0', value: CAT_BTB | 0x01 },
    { name: 'BRCLR1', value: CAT_BTB | 0x03 },
    { name: 'BRCLR2', value: CAT_BTB | 0x05 },
    { name: 'BRCLR3', value: CAT_BTB | 0x07 },
    { name: 'BRCLR4', value: CAT_BTB | 0x09 },
    { name: 'BRCLR5', value: CAT_BTB | 0x0b },
    { name: 'BRCLR6', value: CAT_BTB | 0x0d },
    { name: 'BRCLR7', value: CAT_BTB | 0x0f },
    { name: 'BRN', value: CAT_REL | 0x21 },
    { name: 'BRSET', value: CAT_BTBX | 0x00 },
    { name: 'BRSET0', value: CAT_BTB | 0x00 },
    { name: 'BRSET1', value: CAT_BTB | 0x02 },
    { name: 'BRSET2', value: CAT_BTB | 0x04 },
    { name: 'BRSET3', value: CAT_BTB | 0x06 },
    { name: 'BRSET4', value: CAT_BTB | 0x08 },
    { name: 'BRSET5', value: CAT_BTB | 0x0a },
    { name: 'BRSET6', value: CAT_BTB | 0x0c },
    { name: 'BRSET7', value: CAT_BTB | 0x0e },
    { name: 'BSET', value: CAT_BSCX | 0x10 },
    { name: 'BSET0', value: CAT_BSC | 0x10 },
    { name: 'BSET1', value: CAT_BSC | 0x12 },
    { name: 'BSET2', value: CAT_BSC | 0x14 },
    { name: 'BSET3', value: CAT_BSC | 0x16 },
    { name: 'BSET4', value: CAT_BSC | 0x18 },
    { name: 'BSET5', value: CAT_BSC | 0x1a },
    { name: 'BSET6', value: CAT_BSC | 0x1c },
    { name: 'BSET7', value: CAT_BSC | 0x1e },
    { name: 'BSR', value: CAT_REL | 0xad },
    { name: 'CLC', value: CAT_INH | 0x98 },
    { name: 'CLI', value: CAT_INH | 0x9a },
    { name: 'CLR', value: CAT_DIR_IX1_IX | 0x3f },
    { name: 'CLRA', value: CAT_INH | 0x4f },
    { name: 'CLRX', value: CAT_INH | 0x5f },
    { name: 'CMP', value: CAT_IMM_DIR_EXT_IX1_IX1_IX | 0xa1 },
    { name: 'COM', value: CAT_DIR_IX1_IX | 0x33 },
    { name: 'COMA', value: CAT_INH | 0x43 },
    { name: 'COMX', value: CAT_INH | 0x53 },
    { name: 'CPX', value: CAT_IMM_DIR_EXT_IX1_IX1_IX | 0xa3 },
    { name: 'DB', value: CAT_DB | 0 },
    { name: 'DEC', value: CAT_DIR_IX1_IX | 0x3a },
    { name: 'DECA', value: CAT_INH | 0x4a },
    { name: 'DECX', value: CAT_INH | 0x5a },
    { name: 'DS', value: CAT_DS | 0 },
    { name: 'DW', value: CAT_DW | 0 },
    { name: 'ELSE', value: CAT_ELSE | 0 },
    { name: 'ENDIF', value: CAT_ENDIF | 0 },
    { name: 'EOR', value: CAT_IMM_DIR_EXT_IX1_IX1_IX | 0xa8 },
    { name: 'EQU', value: CAT_EQU | 0 },
    { name: 'IF', value: CAT_IF | 0 },
    { name: 'INC', value: CAT_DIR_IX1_IX | 0x3c },
    { name: 'INCA', value: CAT_INH | 0x4c },
    { name: 'INCLUDE', value: CAT_INCLUDE | 0 },
    { name: 'INCX', value: CAT_INH | 0x5c },
    { name: 'JMP', value: CAT_DIR_EXT_IX1_IX1_IX | 0xac },
    { name: 'JSR', value: CAT_DIR_EXT_IX1_IX1_IX | 0xad },
    { name: 'LDA', value: CAT_IMM_DIR_EXT_IX1_IX1_IX | 0xa6 },
    { name: 'LDX', value: CAT_IMM_DIR_EXT_IX1_IX1_IX | 0xae },
    { name: 'LSL', value: CAT_DIR_IX1_IX | 0x38 },
    { name: 'LSLA', value: CAT_INH | 0x48 },
    { name: 'LSLX', value: CAT_INH | 0x58 },
    { name: 'LSR', value: CAT_DIR_IX1_IX | 0x34 },
    { name: 'LSRA', value: CAT_INH | 0x44 },
    { name: 'LSRX', value: CAT_INH | 0x54 },
    { name: 'MUL', value: CAT_INH | 0x42 },
    { name: 'NEG', value: CAT_DIR_IX1_IX | 0x30 },
    { name: 'NEGA', value: CAT_INH | 0x40 },
    { name: 'NEGX', value: CAT_INH | 0x50 },
    { name: 'NOP', value: CAT_INH | 0x9d },
    { name: 'ORA', value: CAT_IMM_DIR_EXT_IX1_IX1_IX | 0xaa },
    { name: 'ROL', value: CAT_DIR_IX1_IX | 0x39 },
    { name: 'ROLA', value: CAT_INH | 0x49 },
    { name: 'ROLX', value: CAT_INH | 0x59 },
    { name: 'ROR', value: CAT_DIR_IX1_IX | 0x36 },
    { name: 'RORA', value: CAT_INH | 0x46 },
    { name: 'RORX', value: CAT_INH | 0x56 },
    { name: 'RSP', value: CAT_INH | 0x9c },
    { name: 'RTI', value: CAT_INH | 0x80 },
    { name: 'RTS', value: CAT_INH | 0x81 },
    { name: 'SBC', value: CAT_IMM_DIR_EXT_IX1_IX1_IX | 0xa2 },
    { name: 'SEC', value: CAT_INH | 0x99 },
    { name: 'SEI', value: CAT_INH | 0x9b },
    { name: 'STA', value: CAT_DIR_EXT_IX1_IX1_IX | 0xa7 },
    { name: 'STOP', value: CAT_INH | 0x8e },
    { name: 'STX', value: CAT_DIR_EXT_IX1_IX1_IX | 0xaf },
    { name: 'SUB', value: CAT_IMM_DIR_EXT_IX1_IX1_IX | 0xa0 },
    { name: 'SWI', value: CAT_INH | 0x83 },
    { name: 'TAX', value: CAT_INH | 0x97 },
    { name: 'TIMEX', value: CAT_TIMEX | 0 },
    { name: 'TIMEX6', value: CAT_TIMEX6 | 0 },
    { name: 'TST', value: CAT_DIR_IX1_IX | 0x3d },
    { name: 'TSTA', value: CAT_INH | 0x4d },
    { name: 'TSTX', value: CAT_INH | 0x5d },
    { name: 'TXA', value: CAT_INH | 0x9f },
    { name: 'WAIT', value: CAT_INH | 0x8f },
]

export interface inst {
    format: number
    name: string
}

export const ainstOpcodes: inst[] = [
    /* 00 */ { format: DIR2, name: 'brset' },
    /* 01 */ { format: DIR2, name: 'brclr' },
    /* 02 */ { format: DIR2, name: 'brset' },
    /* 03 */ { format: DIR2, name: 'brclr' },
    /* 04 */ { format: DIR2, name: 'brset' },
    /* 05 */ { format: DIR2, name: 'brclr' },
    /* 06 */ { format: DIR2, name: 'brset' },
    /* 07 */ { format: DIR2, name: 'brclr' },
    /* 08 */ { format: DIR2, name: 'brset' },
    /* 09 */ { format: DIR2, name: 'brclr' },
    /* 0A */ { format: DIR2, name: 'brset' },
    /* 0B */ { format: DIR2, name: 'brclr' },
    /* 0C */ { format: DIR2, name: 'brset' },
    /* 0D */ { format: DIR2, name: 'brclr' },
    /* 0E */ { format: DIR2, name: 'brset' },
    /* 0F */ { format: DIR2, name: 'brclr' },
    /* 10 */ { format: BSC, name: 'bset' },
    /* 11 */ { format: BSC, name: 'bclr' },
    /* 12 */ { format: BSC, name: 'bset' },
    /* 13 */ { format: BSC, name: 'bclr' },
    /* 14 */ { format: BSC, name: 'bset' },
    /* 15 */ { format: BSC, name: 'bclr' },
    /* 16 */ { format: BSC, name: 'bset' },
    /* 17 */ { format: BSC, name: 'bclr' },
    /* 18 */ { format: BSC, name: 'bset' },
    /* 19 */ { format: BSC, name: 'bclr' },
    /* 1A */ { format: BSC, name: 'bset' },
    /* 1B */ { format: BSC, name: 'bclr' },
    /* 1C */ { format: BSC, name: 'bset' },
    /* 1D */ { format: BSC, name: 'bclr' },
    /* 1E */ { format: BSC, name: 'bset' },
    /* 1F */ { format: BSC, name: 'bclr' },
    /* 20 */ { format: REL, name: 'bra' },
    /* 21 */ { format: REL, name: 'brn' },
    /* 22 */ { format: REL, name: 'bhi' },
    /* 23 */ { format: REL, name: 'bls' },
    /* 24 */ { format: REL, name: 'bcc' },
    /* 25 */ { format: REL, name: 'blo' },
    /* 26 */ { format: REL, name: 'bne' },
    /* 27 */ { format: REL, name: 'beq' },
    /* 28 */ { format: REL, name: 'bhcc' },
    /* 29 */ { format: REL, name: 'bhcs' },
    /* 2A */ { format: REL, name: 'bpl' },
    /* 2B */ { format: REL, name: 'bmi' },
    /* 2C */ { format: REL, name: 'bmc' },
    /* 2D */ { format: REL, name: 'bms' },
    /* 2E */ { format: REL, name: 'bil' },
    /* 2F */ { format: REL, name: 'bih' },
    /* 30 */ { format: DIR, name: 'neg' },
    /* 31 */ { format: DB, name: 'db' },
    /* 32 */ { format: DB, name: 'db' },
    /* 33 */ { format: DIR, name: 'com' },
    /* 34 */ { format: DIR, name: 'lsr' },
    /* 35 */ { format: DB, name: 'db' },
    /* 36 */ { format: DIR, name: 'ror' },
    /* 37 */ { format: DIR, name: 'asr' },
    /* 38 */ { format: DIR, name: 'lsl' },
    /* 39 */ { format: DIR, name: 'rol' },
    /* 3A */ { format: DIR, name: 'dec' },
    /* 3B */ { format: DB, name: 'db' },
    /* 3C */ { format: DIR, name: 'inc' },
    /* 3D */ { format: DIR, name: 'tst' },
    /* 3E */ { format: DB, name: 'db' },
    /* 3F */ { format: DIR, name: 'clr' },
    /* 40 */ { format: INH, name: 'nega' },
    /* 41 */ { format: DB, name: 'db' },
    /* 42 */ { format: INH, name: 'mul' },
    /* 43 */ { format: INH, name: 'coma' },
    /* 44 */ { format: INH, name: 'lsra' },
    /* 45 */ { format: DB, name: 'db' },
    /* 46 */ { format: INH, name: 'rora' },
    /* 47 */ { format: INH, name: 'asra' },
    /* 48 */ { format: INH, name: 'lsla' },
    /* 49 */ { format: INH, name: 'rola' },
    /* 4A */ { format: INH, name: 'deca' },
    /* 4B */ { format: DB, name: 'db' },
    /* 4C */ { format: INH, name: 'inca' },
    /* 4D */ { format: INH, name: 'tsta' },
    /* 4E */ { format: DB, name: 'db' },
    /* 4F */ { format: INH, name: 'clra' },
    /* 50 */ { format: INH, name: 'negx' },
    /* 51 */ { format: DB, name: 'db' },
    /* 52 */ { format: DB, name: 'db' },
    /* 53 */ { format: INH, name: 'comx' },
    /* 54 */ { format: INH, name: 'lsrx' },
    /* 55 */ { format: DB, name: 'db' },
    /* 56 */ { format: INH, name: 'rorx' },
    /* 57 */ { format: INH, name: 'asrx' },
    /* 58 */ { format: INH, name: 'lslx' },
    /* 59 */ { format: INH, name: 'rolx' },
    /* 5A */ { format: INH, name: 'decx' },
    /* 5B */ { format: DB, name: 'db' },
    /* 5C */ { format: INH, name: 'incx' },
    /* 5D */ { format: INH, name: 'tstx' },
    /* 5E */ { format: DB, name: 'db' },
    /* 5F */ { format: INH, name: 'clrx' },
    /* 60 */ { format: IX1, name: 'neg' },
    /* 61 */ { format: DB, name: 'db' },
    /* 62 */ { format: DB, name: 'db' },
    /* 63 */ { format: IX1, name: 'com' },
    /* 64 */ { format: IX1, name: 'lsr' },
    /* 65 */ { format: DB, name: 'db' },
    /* 66 */ { format: IX1, name: 'ror' },
    /* 67 */ { format: IX1, name: 'asr' },
    /* 68 */ { format: IX1, name: 'lsl' },
    /* 69 */ { format: IX1, name: 'rol' },
    /* 6A */ { format: IX1, name: 'dec' },
    /* 6B */ { format: DB, name: 'db' },
    /* 6C */ { format: IX1, name: 'inc' },
    /* 6D */ { format: IX1, name: 'tst' },
    /* 6E */ { format: DB, name: 'db' },
    /* 6F */ { format: IX1, name: 'clr' },
    /* 70 */ { format: IX, name: 'neg' },
    /* 71 */ { format: DB, name: 'db' },
    /* 72 */ { format: DB, name: 'db' },
    /* 73 */ { format: IX, name: 'com' },
    /* 74 */ { format: IX, name: 'lsr' },
    /* 75 */ { format: DB, name: 'db' },
    /* 76 */ { format: IX, name: 'ror' },
    /* 77 */ { format: IX, name: 'asr' },
    /* 78 */ { format: IX, name: 'lsl' },
    /* 79 */ { format: IX, name: 'rol' },
    /* 7A */ { format: IX, name: 'dec' },
    /* 7B */ { format: DB, name: 'db' },
    /* 7C */ { format: IX, name: 'inc' },
    /* 7D */ { format: IX, name: 'tst' },
    /* 7E */ { format: DB, name: 'db' },
    /* 7F */ { format: IX, name: 'clr' },
    /* 80 */ { format: INH, name: 'rti' },
    /* 81 */ { format: INH, name: 'rts' },
    /* 82 */ { format: DB, name: 'db' },
    /* 83 */ { format: INH, name: 'swi' },
    /* 84 */ { format: DB, name: 'db' },
    /* 85 */ { format: DB, name: 'db' },
    /* 86 */ { format: DB, name: 'db' },
    /* 87 */ { format: DB, name: 'db' },
    /* 88 */ { format: DB, name: 'db' },
    /* 89 */ { format: DB, name: 'db' },
    /* 8A */ { format: DB, name: 'db' },
    /* 8B */ { format: DB, name: 'db' },
    /* 8C */ { format: DB, name: 'db' },
    /* 8D */ { format: DB, name: 'db' },
    /* 8E */ { format: INH, name: 'stop' },
    /* 8F */ { format: INH, name: 'wait' },
    /* 90 */ { format: DB, name: 'db' },
    /* 91 */ { format: DB, name: 'db' },
    /* 92 */ { format: DB, name: 'db' },
    /* 93 */ { format: DB, name: 'db' },
    /* 94 */ { format: DB, name: 'db' },
    /* 95 */ { format: DB, name: 'db' },
    /* 96 */ { format: DB, name: 'db' },
    /* 97 */ { format: INH, name: 'tax' },
    /* 98 */ { format: INH, name: 'clc' },
    /* 99 */ { format: INH, name: 'sec' },
    /* 9A */ { format: INH, name: 'cli' },
    /* 9B */ { format: INH, name: 'sei' },
    /* 9C */ { format: INH, name: 'rsp' },
    /* 9D */ { format: INH, name: 'nop' },
    /* 9E */ { format: DB, name: 'db' },
    /* 9F */ { format: INH, name: 'txa' },
    /* A0 */ { format: IMM, name: 'sub' },
    /* A1 */ { format: IMM, name: 'cmp' },
    /* A2 */ { format: IMM, name: 'sbc' },
    /* A3 */ { format: IMM, name: 'cpx' },
    /* A4 */ { format: IMM, name: 'and' },
    /* A5 */ { format: IMM, name: 'bit' },
    /* A6 */ { format: IMM, name: 'lda' },
    /* A7 */ { format: DB, name: 'db' },
    /* A8 */ { format: IMM, name: 'eor' },
    /* A9 */ { format: IMM, name: 'adc' },
    /* AA */ { format: IMM, name: 'ora' },
    /* AB */ { format: IMM, name: 'add' },
    /* AC */ { format: DB, name: 'db' },
    /* AD */ { format: REL, name: 'bsr' },
    /* AE */ { format: IMM, name: 'ldx' },
    /* AF */ { format: DB, name: 'db' },
    /* B0 */ { format: DIR, name: 'sub' },
    /* B1 */ { format: DIR, name: 'cmp' },
    /* B2 */ { format: DIR, name: 'sbc' },
    /* B3 */ { format: DIR, name: 'cpx' },
    /* B4 */ { format: DIR, name: 'and' },
    /* B5 */ { format: DIR, name: 'bit' },
    /* B6 */ { format: DIR, name: 'lda' },
    /* B7 */ { format: DIR, name: 'sta' },
    /* B8 */ { format: DIR, name: 'eor' },
    /* B9 */ { format: DIR, name: 'adc' },
    /* BA */ { format: DIR, name: 'ora' },
    /* BB */ { format: DIR, name: 'add' },
    /* BC */ { format: DIR, name: 'jmp' },
    /* BD */ { format: DIR, name: 'jsr' },
    /* BE */ { format: DIR, name: 'ldx' },
    /* BF */ { format: DIR, name: 'stx' },
    /* C0 */ { format: EXT, name: 'sub' },
    /* C1 */ { format: EXT, name: 'cmp' },
    /* C2 */ { format: EXT, name: 'sbc' },
    /* C3 */ { format: EXT, name: 'cpx' },
    /* C4 */ { format: EXT, name: 'and' },
    /* C5 */ { format: EXT, name: 'bit' },
    /* C6 */ { format: EXT, name: 'lda' },
    /* C7 */ { format: EXT, name: 'sta' },
    /* C8 */ { format: EXT, name: 'eor' },
    /* C9 */ { format: EXT, name: 'adc' },
    /* CA */ { format: EXT, name: 'ora' },
    /* CB */ { format: EXT, name: 'add' },
    /* CC */ { format: EXT, name: 'jmp' },
    /* CD */ { format: EXT, name: 'jsr' },
    /* CE */ { format: EXT, name: 'ldx' },
    /* CF */ { format: EXT, name: 'stx' },
    /* D0 */ { format: IX2, name: 'sub' },
    /* D1 */ { format: IX2, name: 'cmp' },
    /* D2 */ { format: IX2, name: 'sbc' },
    /* D3 */ { format: IX2, name: 'cpx' },
    /* D4 */ { format: IX2, name: 'and' },
    /* D5 */ { format: IX2, name: 'bit' },
    /* D6 */ { format: IX2, name: 'lda' },
    /* D7 */ { format: IX2, name: 'sta' },
    /* D8 */ { format: IX2, name: 'eor' },
    /* D9 */ { format: IX2, name: 'adc' },
    /* DA */ { format: IX2, name: 'ora' },
    /* DB */ { format: IX2, name: 'add' },
    /* DC */ { format: IX2, name: 'jmp' },
    /* DD */ { format: IX2, name: 'jsr' },
    /* DE */ { format: IX2, name: 'ldx' },
    /* DF */ { format: IX2, name: 'stx' },
    /* E0 */ { format: IX1, name: 'sub' },
    /* E1 */ { format: IX1, name: 'cmp' },
    /* E2 */ { format: IX1, name: 'sbc' },
    /* E3 */ { format: IX1, name: 'cpx' },
    /* E4 */ { format: IX1, name: 'and' },
    /* E5 */ { format: IX1, name: 'bit' },
    /* E6 */ { format: IX1, name: 'lda' },
    /* E7 */ { format: IX1, name: 'sta' },
    /* E8 */ { format: IX1, name: 'eor' },
    /* E9 */ { format: IX1, name: 'adc' },
    /* EA */ { format: IX1, name: 'ora' },
    /* EB */ { format: IX1, name: 'add' },
    /* EC */ { format: IX1, name: 'jmp' },
    /* ED */ { format: IX1, name: 'jsr' },
    /* EE */ { format: IX1, name: 'ldx' },
    /* EF */ { format: IX1, name: 'stx' },
    /* F0 */ { format: IX, name: 'sub' },
    /* F1 */ { format: IX, name: 'cmp' },
    /* F2 */ { format: IX, name: 'sbc' },
    /* F3 */ { format: IX, name: 'cpx' },
    /* F4 */ { format: IX, name: 'and' },
    /* F5 */ { format: IX, name: 'bit' },
    /* F6 */ { format: IX, name: 'lda' },
    /* F7 */ { format: IX, name: 'sta' },
    /* F8 */ { format: IX, name: 'eor' },
    /* F9 */ { format: IX, name: 'adc' },
    /* FA */ { format: IX, name: 'ora' },
    /* FB */ { format: IX, name: 'add' },
    /* FC */ { format: IX, name: 'jmp' },
    /* FD */ { format: IX, name: 'jsr' },
    /* FE */ { format: IX, name: 'ldx' },
    /* FF */ { format: IX, name: 'stx' },
]
